version: "3"

services:
  db:
    image: mongo:5
    restart: always
    container_name: hey-chat
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE=hey-chat
    volumes:
      - ./mongo:/data/hey-chat
